name: SiriusMapIOS

############
# Options
############

options:
  bundleIdPrefix: com.SiriusMapIOS

############
# Configs
############

configs:
  Debug: debug
  Release: release
  Adhoc: release
  Beta: release

############
# Packages
############


############
# Settings
############

# settings:
  # PRODUCT_BUNDLE_IDENTIFIER: $(AS_BUNDLE_IDENTIFIER)

targets:
  SiriusMapIOS:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [SiriusMapIOS]
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        SWIFT_VERSION: 5.2
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        TARGETED_DEVICE_FAMILY: 1
