name: SiriusMobileIOS
# include:
#  - base_spec.yml
options:
  bundleIdPrefix: com.SiriusMobileIOS
packages:
  Yams:
    url: https://github.com/jpsim/Yams
    from: 2.0.0
targets:
  SiriusMobileIOS:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [SiriusMobileIOS]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
        release:
          CUSTOM_BUILD_SETTING: my_release_value
