name: Flutter

on:
  push:
    branches: [ "develop", "flutter_ci" ,"flutter_ci_test" ]
  pull_request:
    branches: [ "develop", "flutter_ci", "flutter_ci_test" ]
jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: |
          cd flutter_sirius_map
          flutter pub get
          flutter gen-l10n 
      - name: Analyze project source
        run: flutter analyze
      - name: Format check
        run: dart format . --set-exit-if-changed
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: |
          cd flutter_sirius_map
          flutter pub get
          flutter gen-l10n 
      - name: Run tests
        run: |
          cd flutter_sirius_map
          flutter test
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: |
          cd flutter_sirius_map
          flutter pub get
          flutter gen-l10n 
      - name: Flutter build android
        run: |
          cd flutter_sirius_map
          flutter build apk
      - name: Set Env Artifact 
        run: |
          cd flutter_sirius_map
          cd ${{ env.main_project_module }}/build/app/outputs/flutter-apk/
          files=(*)
          echo "generated_name_aab=${files[0]%.*}" >> $GITHUB_ENV

      
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/app/outputs/flutter-apk/


  build-ios:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: |
          cd flutter_sirius_map
          flutter pub get
          flutter gen-l10n 
      - name: Flutter build ios
        run: |
          cd flutter_sirius_map
          cd ios 
          pod install
          cd ..
          flutter build ios --no-codesign
