name: Flutter

on:
  push:
    branches: [ "develop", "flutter_ci","flutter_ci_test" ]
  pull_request:
    branches: [ "develop", "flutter_ci","flutter_ci_test" ]
jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Switching to Flutter dependencies
        run: cd ../../flutter_sirius_map
      - name: Install dependencies
        run: flutter pub get
      - name: Build runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze project source
        run: flutter analyze
      - name: Format check
        run: dart format . --set-exit-if-changed
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Switching to Flutter dependencies
        run: cd ../../flutter_sirius_map
      - name: Install dependencies
        run: flutter pub get
      - name: Build runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        run: flutter test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Switching to Flutter dependencies
        run: cd ../../flutter_sirius_map
      - name: Install dependencies
        run: flutter pub get
      - name: Build runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Flutter build
        run: flutter build apk --flavor dev -t lib/main_dev.dart --dart-define=KEY_BEARER=${{secrets.KEY_BEARER}}
